[package]
name = "voxelgame"
version = "0.0.1"
authors = ["trashbyte"]

[dependencies]
cgmath = { version = "0.16.1", features = [ "swizzle" ] }
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
image = "0.19.0"
winit = "0.16.0"
time = "0.1.38"
rand = "0.5.5"
noise = "0.5.1"